version: "3.8"
services:
  db:
    image: mysql:8.0.28
    cap_add:
      - SYS_NICE
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: file_db
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ../range-service/db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db:
    driver: local